### ISSUE TITLE
Any idea about the discriminator architecture?

### ISSUE THREAD

**Issue by gnsrla12** [rishikksh20/HiFiplusplus-pytorch#3]
Hi, amazing work! I'm also trying to implement HIFI++ but I can't find any info regarding the discriminator architecture. In the paper they claim to have designed a much smaller MSD discriminators. Do you have any idea?

` Further, we
demonstrate that we can substitude MSD discriminators that
operate on different input resolutions for identical much
smaller discriminators that process the waveform on the
initial resolution.`

**Comment by rishikksh20** [comment]
Use the same architecture as Melgan's discriminator but without Avg Pool.

**Comment by gnsrla12** [comment]
Thanks for the reply. But in your code you are using HIFIGAN discriminator architecture, instead of the MelGAN discriminator, without Avg Pooling. Any reason?

**Comment by rishikksh20** [comment]
HifiGAN's msd discriminator is same as Melgan disc
