### ISSUE TITLE
may be a mistake in MRF？

### ISSUE THREAD

**Issue by azraelkuan** [rishikksh20/HiFiplusplus-pytorch#4]
it seems the paper use a serial ResBlock(kernel size=3,7,11) but the coder use parallel ResBlock
![image](https://user-images.githubusercontent.com/23380152/160524678-e396c18b-e2cf-4e12-894a-15e1ad39bfa3.png)

https://github.com/rishikksh20/HiFiplusplus-pytorch/blob/8be0d0e0092d4f609c37bfbeede5a9ad9bd7470a/models.py#L120

I think this is the key of high quality, but the RTF will be much bigger than melgan and hifigan v2. MAC is not a performance indicator.

**Comment by rishikksh20** [comment]
Yes, this repo is still in WIP (work in progress) mode, actually, I try to understand the importance of each and every module change made in the original hifigan model one by one like Ablation studies. I am also planning to include the findings of the new hifi-gan based paper iSTFTnet in this repo to make it even faster and better. I will update this repo with the exact same architecture similar to the paper once I complete my understanding.

**Comment by rishikksh20** [comment]
Currently, I have been training 4 different versions of HiFi++, once training is over, I will update this repo with my findings.

**Comment by azraelkuan** [comment]
thanks!

**Comment by hdmjdp** [comment]
> Currently, I have been training 4 different versions of HiFi++, once training is over, I will update this repo with my findings.

Maybe the author just misunderstand it, have you tried his MRF?
